/**
 * Seedance 2.0 structured-prompt serializer + the fields it needed (2026-08-31).
 *
 * WHERE THIS CAME FROM: Khian supplied a Seedance prompt recipe and asked whether it could be
 * used — both as a checklist of what to LOOK FOR in a source video, and as the SHAPE of what
 * the app emits so output is pasteable rather than prose to reshape by hand.
 *
 * Most of the recipe the app already exceeded (camera physics, realism tells, beat structure).
 * Four things it genuinely lacked, all now captured: a CAST (the app had no concept of a
 * second person), SPEAKER attribution on dialogue, background activity, and end behaviour.
 *
 * THE KEY DESIGN DECISION, and what most of this file guards: the JSON is DERIVED from the
 * already-enforced beats, never generated by the model. A separately generated JSON would be
 * a second representation of the same beat, and only the prose motionPrompt carries the
 * hold-body directive, the secondary-motion cap, the ambient line, the negation pair and the
 * humanization lint. Two plausible-looking representations that disagree is worse than one.
 *
 * Run: npm test
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { buildSeedancePrompt, SEEDANCE_NEGATIVES } from '../worker/src/generate/seedance';
import { BeatSchema, CastMemberSchema, PacingSchema } from '../shared/schemas';
import type { FormatDna, Ideation, ModelProfile } from '../shared/contract';

// ── the new input fields ──

test('cast members validate, including the off-camera case', () => {
  assert.ok(CastMemberSchema.safeParse({
    id: 'person_2', role: 'shop assistant',
    appearance: 'tall man, 30s, short dark hair', wardrobe: 'black polo, name badge',
  }).success);
  // The commonest case in real UGC: a friend filming who is never in frame.
  assert.ok(CastMemberSchema.safeParse({
    id: 'friend', role: 'friend filming', appearance: '', wardrobe: '', offCamera: true,
  }).success);
});

test('beat.speaker and beat.delivery are optional — pre-2026-08-31 rows still parse', () => {
  const bare = {
    index: 0, clipIndex: 0, startSec: 0, endSec: 2, action: 'a', rightHand: 'r',
    leftHand: 'l', cameraMove: 'static', framing: 'f', expressionEnergy: 'e', startsOnCut: true,
  };
  assert.ok(BeatSchema.safeParse(bare).success);
  assert.ok(BeatSchema.safeParse({ ...bare, speaker: 'person_2', delivery: 'laughing' }).success);
});

test('pacing.endBehavior is a closed set — abrupt / resolved / loop', () => {
  const base = { totalDurationSec: 8, cutCount: 0, isOneShot: true, rhythm: 'r', energy: 'e' };
  assert.ok(PacingSchema.safeParse({ ...base, endBehavior: 'abrupt' }).success);
  assert.equal(PacingSchema.safeParse({ ...base, endBehavior: 'fade' }).success, false);
  assert.ok(PacingSchema.safeParse(base).success, 'still optional for stored rows');
});

// ── the serializer ──

function fixture(over: { cast?: unknown[]; endBehavior?: string; bg?: string } = {}) {
  const dna = {
    title: 'Prank', formatType: 'skit',
    setting: {
      locationType: 'suburban kitchen', timeOfDay: 'evening', lighting: 'overhead warm',
      keyProps: ['spoon', 'pan'], colorPalette: 'warm', mood: 'playful',
      ...(over.bg !== undefined ? { backgroundActivity: over.bg } : {}),
    },
    wardrobeRole: { role: 'at-home', garments: ['grey tee'], stylingNotes: '' },
    pacing: {
      totalDurationSec: 11, cutCount: 1, isOneShot: false, rhythm: 'two quick beats',
      energy: 'warm', ...(over.endBehavior ? { endBehavior: over.endBehavior } : {}),
    },
    camera: { setup: 'propped_on_surface', dynamics: { motionSignature: 'locked-off phone on the counter, faint micro-shake' } },
    aesthetic: {
      grade: 'raw ungraded, warm white balance', promptAnchor: 'raw iPhone kitchen footage, NOT cinematic',
      antiCinematic: 'no colour grade, no shallow depth of field',
      realismTells: ['sensor-noise-in-shadows'], realismMarkers: ['blown window highlight'],
      lightingDirection: 'overhead, slightly behind', colorTempK: '~3000K', practicals: ['ceiling LED'],
    },
    audio: { kind: 'ambient', roomTone: 'extractor fan hum, pan sizzling' },
    ...(over.cast ? { cast: over.cast } : {}),
  } as unknown as FormatDna;

  const ideation = {
    index: 0, title: 'T', videoFormat: 'MULTI_CLIP', clipCount: 2, targetDurationSec: 11,
    beats: [
      { clipIndex: 0, durationSec: 6, action: 'she tastes the sauce', camera: 'static, chest height', dialogue: 'oh no.', speaker: 'subject' },
      { clipIndex: 1, durationSec: 5, action: 'she fans her mouth', camera: 'static', dialogue: undefined },
    ],
    continuityLock: { wardrobeExact: 'grey cotton tee, black leggings' },
  } as unknown as Ideation;

  const profile = { voice: { accent: 'warm Australian lilt' } } as unknown as ModelProfile;
  return { ideation, dna, profile };
}

test('the subject is NEVER described — locked refs supply her, text would fight them', () => {
  const { ideation, dna, profile } = fixture();
  const p = buildSeedancePrompt(ideation, dna, profile);
  const subject = p.people.find((x) => x.id === 'subject')!;
  assert.match(subject.appearance, /do not describe/i);
  assert.match(subject.appearance, /reference images/i);
  // Wardrobe DOES come through — it is a costume decision, not identity.
  assert.equal(subject.wardrobe, 'grey cotton tee, black leggings');
});

test('cast members ARE described — they have no reference image', () => {
  const { ideation, dna, profile } = fixture({
    cast: [{ id: 'person_2', role: 'flatmate', appearance: 'short woman, 20s, curly hair', wardrobe: 'hoodie' }],
  });
  const p = buildSeedancePrompt(ideation, dna, profile);
  const second = p.people.find((x) => x.id === 'person_2')!;
  assert.match(second.appearance, /curly hair/);
  assert.equal(second.wardrobe, 'hoodie');
});

test('an off-camera cast member is flagged so nothing tries to render them', () => {
  const { ideation, dna, profile } = fixture({
    cast: [{ id: 'friend', role: 'friend filming', appearance: '', wardrobe: '', offCamera: true }],
  });
  const p = buildSeedancePrompt(ideation, dna, profile);
  const friend = p.people.find((x) => x.id === 'friend')!;
  assert.match(friend.role, /OFF CAMERA/);
  assert.match(friend.appearance, /never visible/);
});

test('a silent beat still gets a scene_event, with line and delivery NULL', () => {
  // Explicit in the recipe, and it matters: skipping silent moments loses half the timeline.
  const { ideation, dna, profile } = fixture();
  const p = buildSeedancePrompt(ideation, dna, profile);
  assert.equal(p.scene_events.length, 2);
  assert.equal(p.scene_events[1]!.line, null);
  assert.equal(p.scene_events[1]!.delivery, null);
  assert.match(p.scene_events[1]!.action, /fans her mouth/);
});

test('a spoken beat carries the line, the speaker, and the profile accent as delivery', () => {
  const { ideation, dna, profile } = fixture();
  const p = buildSeedancePrompt(ideation, dna, profile);
  assert.equal(p.scene_events[0]!.line, 'oh no.');
  assert.equal(p.scene_events[0]!.speaker, 'subject');
  assert.match(p.scene_events[0]!.delivery!, /Australian/);
});

test('a VO-labelled dialogue field is stripped of its operator prefix', () => {
  // rules.ts prefixes voiceover lines with "VO (…never lip-sync): " for the operator card.
  // That label must not end up inside the spoken line handed to a video model.
  const { ideation, dna, profile } = fixture();
  ideation.beats[0]!.dialogue = 'VO (off-camera voiceover — record separately, never lip-sync): she is not ready';
  const p = buildSeedancePrompt(ideation, dna, profile);
  assert.equal(p.scene_events[0]!.line, 'she is not ready');
});

test('end_behavior defaults to ABRUPT, not resolved', () => {
  // A clean resolved ending is one of the strongest "this was produced" tells, so the safe
  // default is the scrappy one.
  const { ideation, dna, profile } = fixture();
  assert.match(buildSeedancePrompt(ideation, dna, profile).end_behavior, /abruptly mid-action/);
});

test('end_behavior follows the source when it was recorded', () => {
  const { ideation, dna, profile } = fixture({ endBehavior: 'loop' });
  assert.match(buildSeedancePrompt(ideation, dna, profile).end_behavior, /loop seamlessly/);
});

test('background_activity falls back to an INSTRUCTION, never an empty string', () => {
  // An unstated background is what produces a dead, empty set — humanization law 8 exists to
  // prevent exactly that, so the fallback has to carry the law rather than say nothing.
  const { ideation, dna, profile } = fixture();
  const p = buildSeedancePrompt(ideation, dna, profile);
  assert.match(p.background_activity, /alive but secondary/);
  assert.match(p.background_activity, /nobody looking at camera/);
});

test('background_activity uses the source pattern when one was captured', () => {
  const { ideation, dna, profile } = fixture({ bg: 'a flatmate crosses behind her once, not looking up' });
  assert.match(buildSeedancePrompt(ideation, dna, profile).background_activity, /crosses behind her once/);
});

test('camera_logic comes from the measured motion signature, not a generic phrase', () => {
  const { ideation, dna, profile } = fixture();
  assert.match(buildSeedancePrompt(ideation, dna, profile).camera_logic, /locked-off phone on the counter/);
});

test('the negative prompt carries every harvested term plus our own anti-cinematic line', () => {
  const { ideation, dna, profile } = fixture();
  const neg = buildSeedancePrompt(ideation, dna, profile).negative_prompt;
  for (const term of SEEDANCE_NEGATIVES) assert.ok(neg.includes(term), `missing: ${term}`);
  assert.match(neg, /no shallow depth of field/, 'our own antiCinematic line must survive');
});

test('imperfections lead with the FIXED realism tells, then free-form markers', () => {
  // The enum tells map to deterministic prompt tokens elsewhere; ordering keeps them primary.
  const { ideation, dna, profile } = fixture();
  const imp = buildSeedancePrompt(ideation, dna, profile).imperfections;
  assert.equal(imp[0], 'sensor-noise-in-shadows');
  assert.ok(imp.includes('blown window highlight'));
});

test('shots timeline is built from real beat durations, in order', () => {
  const { ideation, dna, profile } = fixture();
  const p = buildSeedancePrompt(ideation, dna, profile);
  assert.equal(p.shots[0]!.time, '0:00–0:06');
  assert.equal(p.shots[1]!.time, '0:06–0:11');
});

test('the serializer never throws on a sparse ideation', () => {
  // It runs inside a paid generation. A missing optional field must degrade, never fail —
  // the prose prompts are the primary output and must survive a serializer problem.
  const sparse = { index: 0, beats: [], videoFormat: 'ONE_SHOT', clipCount: 1 } as unknown as Ideation;
  const bare = { pacing: {}, setting: {}, camera: {} } as unknown as FormatDna;
  const p = buildSeedancePrompt(sparse, bare, {} as unknown as ModelProfile);
  assert.equal(p.scene_events.length, 0);
  assert.ok(p.negative_prompt.length > 0, 'the negatives are constants and must always be there');
  assert.ok(p.style.length > 0);
});
